### ISSUE TITLE
PermissionSet#serialize breaks with rdflib.js 0.13.0

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-permissions#16]
copy from gitter: https://gitter.im/solid/chat?at=587168559e6f00e74a0b219f

I don't understand this, solid-permissions in serialize https://github.com/solid/solid-permissions/blame/c60141eaed6d168cf52b13f55fab0afcf5a28fec/src/permission-set.js#L755-L773
does
```js
    let target = null
    let base = null
    return new Promise((resolve, reject) => {
rdf.serialize(target, graph, base, contentType, (err, result) => { //...
```
and rdflib.js in serialize https://github.com/linkeddata/rdflib.js/blame/master/src/serialize.js#L12
does
```js
base = base || target.uri
```
which results in `"Cannot read property 'uri' of null"`
https://github.com/solid/solid-permissions/blob/c60141eaed6d168cf52b13f55fab0afcf5a28fec/package.json#L50
`"rdflib": "^0.12.1"`
since solid-client depends on `"rdflib": "^0.13.0"` solid-permissions it uses can't serialize permission set

it looks like @timbl made 17 days ago change to rdflib which made latest rdflib.js incompatible with current implementation of solid-permissions PermissionsSet#serialize

### TODO
* [ ] update rdflib dev dependency to "0.13.0"
* [ ] fix PermissionSet#serialize

**Comment by elf-pavlik** [comment]
merging #15 should solve it!

**Comment by kjetilk** [comment]
Could you please check that it is working, @elf-pavlik ?

**Comment by kjetilk** [comment]
It seems to me that this issue is solved, since the branch has been merged and we have the same rdflib dep.
