### ISSUE TITLE
Authorization objects don't represent instances of acl:Authorization

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-permissions#17]
This issue serves as dedicated space to the issue I mentioned in https://github.com/solid/solid-permissions/pull/15#discussion_r95071284

[WAC spec](https://github.com/solid/web-access-control-spec) doesn't define `acl:agent` as functional property and allows relating with it multiple agents to single instance of `acl:Authorization`.

Implementation of Authorization in solid-permissions module, [makes different assumption](https://github.com/solid/solid-permissions/blob/823c67c9456a3ce86aaf02cebe3a5e142b933510/src/authorization.js#L16-L23)
> Models an individual authorization object, for a single resource and for a single webId (either agent or agentClass). See the comments at the top of the PermissionSet module for design assumptions.

This mismatch suggests that current implementation doesn't implement round-trip between parsed instances of `acl:Authorization` and solid-permossions `Authorization` objects.

For example, taking modified version of [example from WAC spec](https://github.com/solid/web-access-control-spec#example-wac-document)

```ttl
# Contents of https://alice.databox.me/docs/file1.acl
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

<#authorization1>
    a acl:Authorization;
    acl:agent 
      <https://alice.databox.me/profile/card#me> ,  # Alice's WebID
      <https://bob.databox.me/profile/card#me> ;  # Bob's WebID
    acl:accessTo <https://alice.databox.me/docs/file1>;
    acl:mode
        acl:Read, acl:Write, acl:Control .
```

`PermissionSet#initFromGraph` will create from this single instance of `acl:Authorization` two solid-permissions Autnorization objects (+2 virtual ones for ACL resource itself). Later `PermissionSet#buildGraph()` used by `PermisionSet#serialize` will produce:

```ttl
@prefix n0: <http://www.w3.org/ns/auth/acl#>.
@prefix docs: <./>.
@prefix c: </profile/card#>.
@prefix c0: <https://bob.databox.me/profile/card#>.

<#https://alice.databox.me/profile/card#me-https://alice.databox.me/docs/file1-accessTo>
   a    n0:Authorization;
   n0:accessTo docs:file1;
   n0:agent c:me;
   n0:mode n0:Control, n0:Read, n0:Write.

<#https://bob.databox.me/profile/card#me-https://alice.databox.me/docs/file1-accessTo>
    a    n0:Authorization;
    n0:accessTo docs:file1;
    n0:agent c0:me;
    n0:mode n0:Control, n0:Read, n0:Write.
```

### PROPOSAL

1. rename Authorization to Permission in solid-permissions
2. PermissionSet should handle creating Permissions based on instances of `acl:Authorizations` and have responsibility of serializing them back based on its internal Permissions. It should also preserve original IRIs of each `acl:Authorization`.

#### ALTERNATIVE

WAC spec should define `acl:agent` as functional property and adopt approach implemented in solid-permissions. This would make breaking change to WAC and render many existing ACLs invalid

**Comment by dmitrizagidulin** [comment]
Thanks @elf-pavlik! We'll be addressing this in issue #23 (renaming the Authorization class). 

The current decision is not to preserve the original Authorization hash fragment URIs, though. For two reasons - 1) to do so would require some extensive refactoring, and 2) preserving them implies that we should encourage other apps to link to individual authorizations, which is not the case at all (since they're fairly arbitrary). What matters is the whole `.acl` graph.

Closing this issue for now.

**Comment by kjetilk** [comment]
Yup, but we may reconsider preserving the URIs at some later point, as URI aliasing is generally evil.
