### ISSUE TITLE
Check Origin permissions separately from agent permissions

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-permissions#20]
Per conversation with @timbl, need to change how this library implements the semantics of agent and origin filtering.

Currently, the code asks "Are there any authorizations which fulfill *all 4* of the following rules: the access mode, the resource, the agent, and the origin".

Need to change it to: "Are there any authorizations which fulfill *all 3* of the following rules: access mode, resource, and agent. *In addition*, are there any other authorizations that match the origin (for that access mode & resource)."

**Comment by RubenVerborgh** [comment]
What would the "in addition" part look like? We just give back two sets of rules? And why?

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh I think @timbl can explain the semantics better.

**Comment by timbl** [comment]
Let me try to explain.  Bother the agent and the webapp (origin) are in a positiion to  attack the data. Therefore they must both be trusted. The data can only by accessed if BOTH the agent and the origin (if  any) have access.

The requiremnt is then that for EACH mode needed, there is some authorization ?a for which 
```
?a  agent $agent; mode $M;  accessTo $DOC 
```
AND ALSO for each mode needed there is one wsuch that
```
?a  origin $origin; mode $M;  accessTo $DOC 
```
where those can all be satisfied by completely different authorization nodes in the graph.
I though that the bug that the agent and origin had to be  authorized by the same node was fixed ages ago.

**Comment by kjetilk** [comment]
Indeed, this is not a problem in the current code, https://github.com/solid/solid-permissions/blob/master/src/permission-set.js#L436 does this.
