### ISSUE TITLE
Add list of trusted origins

### ISSUE THREAD

**Issue by kjetilk** [solid/solid-permissions#26]
We should have a list of trusted origins. 

Our own origin must not be on that list by default, but a domain that we control should be there by default.

**Comment by kjetilk** [comment]
This will be fixed by implementing 
https://github.com/solid/solid-permissions/issues/26

**Comment by melvincarvalho** [comment]
Agreed!  

Question : should github.io be on the trusted list?

**Comment by RubenVerborgh** [comment]
> Question : should github.io be on the trusted list?

It would not be, given that anyone can put anything there, including malicious apps. However, you can put specific subdomains there yourself.

**Comment by kjetilk** [comment]
@melvincarvalho I think the key to understand why github.io shouldn't be on the list, is the sentence in the spec that says:

> All scripts running on the same origin are assumed to be run by the same social entity, and so trusted to the same extent.

which is clearly not the case with github.io, there are many different social entities that write there.

**Comment by kjetilk** [comment]
@timbl can you let us know when we have an actual, registered domain for this, so that we can create an origin from that and include that as a default?

**Comment by kjetilk** [comment]
@justinwb , @johnbizguy : Have you secured the domain that we will use for trusted origins?
